// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC81oT6RT_9OqGb-ZHvMJRshHx6BDxN64w',
    appId: '1:720359756657:web:fea4654600f4a62e309cd0',
    messagingSenderId: '720359756657',
    projectId: 'sportshub-a9e9f',
    authDomain: 'sportshub-a9e9f.firebaseapp.com',
    databaseURL: 'https://sportshub-a9e9f-default-rtdb.firebaseio.com',
    storageBucket: 'sportshub-a9e9f.appspot.com',
    measurementId: 'G-YMZRJMJEBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxTqPwY2UU52PS6UoeIjtudzyyCKtSON8',
    appId: '1:720359756657:android:b692fdf03d235bab309cd0',
    messagingSenderId: '720359756657',
    projectId: 'sportshub-a9e9f',
    databaseURL: 'https://sportshub-a9e9f-default-rtdb.firebaseio.com',
    storageBucket: 'sportshub-a9e9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmbACMx9R5xOyo0ECQq5JKyfnGkJRQoHs',
    appId: '1:720359756657:ios:3ddb37da90c15054309cd0',
    messagingSenderId: '720359756657',
    projectId: 'sportshub-a9e9f',
    databaseURL: 'https://sportshub-a9e9f-default-rtdb.firebaseio.com',
    storageBucket: 'sportshub-a9e9f.appspot.com',
    iosBundleId: 'com.example.sportsHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmbACMx9R5xOyo0ECQq5JKyfnGkJRQoHs',
    appId: '1:720359756657:ios:3ddb37da90c15054309cd0',
    messagingSenderId: '720359756657',
    projectId: 'sportshub-a9e9f',
    databaseURL: 'https://sportshub-a9e9f-default-rtdb.firebaseio.com',
    storageBucket: 'sportshub-a9e9f.appspot.com',
    iosBundleId: 'com.example.sportsHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC81oT6RT_9OqGb-ZHvMJRshHx6BDxN64w',
    appId: '1:720359756657:web:665fa63cda4f4ddc309cd0',
    messagingSenderId: '720359756657',
    projectId: 'sportshub-a9e9f',
    authDomain: 'sportshub-a9e9f.firebaseapp.com',
    databaseURL: 'https://sportshub-a9e9f-default-rtdb.firebaseio.com',
    storageBucket: 'sportshub-a9e9f.appspot.com',
    measurementId: 'G-Y5ZVBN97W9',
  );
}
